### PR TITLE
Feature: set donation type as category to GA event

### LINKED ISSUE #47: fix: track renewal payments
# Bug Report

## User Story

As an admin, I want to GA to track renewal/subscription payments so that I have more realistic ecommerce data from my site..

## Current Behavior

The first payment registers but subsequent payments do not.

## Expected Behavior

All completed payments should be registered.

## Bug Type

- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Setup GA add-on
2. Create a recurring payment
3. Check GA dashboard, only the first payment is tracked.

## Related

https://secure.helpscout.net/conversation/1068898668/56025?folderId=672194

## Acceptance Criteria

- [x] Renewal payments send information to Google Analytics

### PR DESCRIPTION
**Pull request by ravinderk**
Resolves #47

## Description

This pull request implements Google Analytics tracking for renewals. A category (`One-Time`, `Subscription`, or `Renewal`) will be added to item information.

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Review by JasonTheAdams — APPROVED** [review]
Looks solid, @ravinderk! Let's get this over to QA!

**Comment by ravinderk** [comment]
> Looks solid, @ravinderk! Let's get this over to QA!

👍

**Comment by ravinderk** [comment]
@JasonTheAdams After debugging the Google Analytic event data, I found a few bugs which have been fixed.

- For renewal donations, the `refund` and `purchase` event do not appear in the real-time dashboard because  `client id` and `session id` was incorrect. I was fetching them from renewal donation metadata instead of parent donation metadata.
- `item_category_3` has an incorrect value for the subscription because I was looking for the subscription id in the donation model, but it does not set for subscription initial payment.
- `item_category_3` does not track correctly for an item for iframe donation on the client because I did not add logic. It is working only for the legacy form template.

Note: For renewal donation, `refund` and `purchase` events will appear in the real-time dashboard in Google analytics.

**Review by Benunc — APPROVED** [review]
This has been tested on the QA site, and categories 1, 2, and 3 are now showing correctly.

**Pull request merged**
